version: '3.9'

services:
  db:
    build: ./db
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=ACAB_DB
    volumes:
      - ./seed:/seed
      - ./data:/var/lib/postgresql/data
  api:
    build: ./api
    container_name: api
    restart: always
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=ACAB_DB
      - DB_HOST=db
    depends_on:
      - db
