name: Lint and Test

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        name: golangci-lint
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.29
          working-directory: api
      - uses: Jerome1337/gofmt-action@v1.0.4
        name: gofmt
        with:
          gofmt-path: './'
          gofmt-flags: '-l -d'
  integration-test:
      name: integration test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: extractions/setup-just@v1
        - name: integration-tests
          env:
            DB_USERNAME: postgres
            DB_PASSWORD: postgres
          run: |
            just build
            just test-int
