name: Lint and Test

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Set up QEMU
        with:
          token: ${{ github.token }}
      - uses: golangci/golangci-lint-action@v2
        name: golangci-lint
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.29
          working-directory: api
      - uses: actions/setup-go@v2
        name: Set up Go
        with:
          go-version: 1.16
      - name: Build
        working-directory: api
        run: go build -v ./...
      - name: Test
        working-directory: api
        run: go test -v ./...