name: Build on Release

on:
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Set up QEMU
      - uses: docker/setup-qemu-action@v1
        name: Set up Docker Buildx
      - uses: docker/setup-buildx-action@v1
        name: Login to DockerHub
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Set release verison env
        run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV
      - name: Build and push API
        uses: docker/build-push-action@v2
        with:
          context: ./api
          platforms: linux/amd64
          push: true
          tags: |
            sdsa/spd-lookup-api:$RELEASE_VERSION
            sdsa/spd-lookup-api:latest
      - name: Build and push DB
        uses: docker/build-push-action@v2
        with:
          context: ./db
          platforms: linux/amd64
          push: true
          tags: |
            sdsa/spd-lookup-db:$RELEASE_VERSION
            sdsa/spd-lookup-db:latest
